package com.carolina.recipesapp.model

val IngredientsList = listOf(
    Pair("Spaghetti", "\uD83C\uDF5D"),
    Pair("Ground beef", "\uD83E\uDD69"),
    Pair("Tomatoes", "\uD83C\uDF45"),
    Pair("Onion", "\uD83E\uDDC5"),
    Pair("Garlic", "\uD83E\uDDC4"),
    Pair("Carrot", "\uD83E\uDD55"),
    Pair("Celery", "\uD83E\uDD52"),
    Pair("Tomato paste", "\uD83E\uDD6B"),
    Pair("Red wine", "\uD83C\uDF77"),
    Pair("Olive oil", "\uD83E\uDED2"),
    Pair("Chicken breasts", "\uD83C\uDF57"),
    Pair("Lemon", "\uD83C\uDF4B"),
    Pair("Rosemary", "\uD83C\uDF31"),
    Pair("Thyme", "\uD83C\uDF3F"),
    Pair("Salt", "\uD83E\uDDC2"),
    Pair("Black pepper", "\uD83E\uDDC2"),
    Pair("Paprika", "\uD83E\uDDC2"),
    Pair("Honey", "\uD83C\uDF6F"),
    Pair("Chickpeas", "\uD83E\uDED8"),
    Pair("Coconut milk", "\uD83E\uDD5B"),
    Pair("Spinach", "\uD83C\uDF6F"),
    Pair("Tortillas", "\uD83E\uDED3"),
    Pair("Avocado", "\uD83E\uDD51"),
    Pair("Potatoes", "\uD83E\uDD54"),
    Pair("Butter", "\uD83E\uDDC8"),
    Pair("Milk", "\uD83E\uDD5B"),
    Pair("Mango", "\uD83E\uDD6D"),
    Pair("Jalapeno", "\uD83C\uDF36️"),
    Pair("Shrimp", "\uD83E\uDD90"),
    Pair("Rice", "\uD83C\uDF5A"),
    Pair("Cornstarch", "\uD83C\uDF3D"),
    Pair("Cooked rice", "\uD83C\uDF5A"),
    Pair("Parmesan cheese", "\uD83E\uDDC0"),
    Pair("Croutons", "\uD83E\uDD56"),
    Pair("Red onion", "\uD83E\uDDC5"),
    Pair("Eggplant", "\uD83C\uDF46"),
    Pair("Ginger", "\uD83E\uDEDA"),
    Pair("Sake", "\uD83C\uDF76"),
    Pair("Bay leaf", "\uD83C\uDF43"),

)
